# Generated by Django 3.2.15 on 2022-10-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='subcategories',
            field=models.ManyToManyField(to='urunler.Subcategory'),
        ),
    ]
