# Generated by Django 3.2.15 on 2022-10-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_auto_20221031_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sepet',
            old_name='kullanici',
            new_name='user',
        ),
    ]
