# Generated by Django 3.2.15 on 2022-10-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_rename_urun_sepet_makaleler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sepet',
            old_name='makaleler',
            new_name='urunler',
        ),
    ]
