# Generated by Django 3.2.15 on 2022-10-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sepet',
        ),
    ]
