# Generated by Django 3.2.15 on 2022-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0011_auto_20221031_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='adet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
