# Generated by Django 3.2.15 on 2022-10-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0012_sepet_adet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
