# Generated by Django 3.2.15 on 2022-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0015_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(blank=True, to='urunler.ShoppingCartItem'),
        ),
    ]
