# Generated by Django 3.2.15 on 2022-10-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0016_auto_20221031_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
