# Generated by Django 3.2.15 on 2022-10-31 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0017_alter_shoppingcartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
