# Generated by Django 3.2.15 on 2022-11-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0019_sepettencikar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SepettenCikar',
        ),
    ]
