# Generated by Django 3.2.15 on 2022-11-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0021_product_useritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
