# Generated by Django 3.2.15 on 2022-11-01 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunler', '0023_alter_sepet_adet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urun',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='urun',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='no',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='resim',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='urun_aciklama',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='urun_adi',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='urun_ekipman',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='urun_firma',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='urun_fiyat',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='urun_marka',
        ),
        migrations.AddField(
            model_name='urun',
            name='author',
            field=models.CharField(blank=True, default='admin', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='urunler.kategori'),
        ),
        migrations.AddField(
            model_name='urun',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='urun',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
