# Generated by Django 3.2.15 on 2022-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0024_auto_20221101_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
