# Generated by Django 3.2.15 on 2022-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0025_alter_urun_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
