# Generated by Django 3.2.15 on 2022-11-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0026_alter_urun_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
