# Generated by Django 3.2.15 on 2022-11-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0027_alter_urun_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
