# Generated by Django 3.2.15 on 2022-11-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0028_alter_urun_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='author',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
