# Generated by Django 3.2.15 on 2022-11-01 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0029_alter_urun_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urun',
            options={},
        ),
        migrations.RemoveField(
            model_name='urun',
            name='author',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='category',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='created',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='description',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='image',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='price',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='title',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='updated',
        ),
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.kategori'),
        ),
        migrations.AddField(
            model_name='urun',
            name='no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.serino'),
        ),
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='urunler/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='subcategories',
            field=models.ManyToManyField(to='urunler.Subcategory'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_aciklama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_adi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_ekipman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_firma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_fiyat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_marka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
