# Generated by Django 3.2.15 on 2022-11-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0031_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='resim2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
