# Generated by Django 3.2.15 on 2022-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0033_auto_20221102_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='images/kategoriler'),
        ),
    ]
