# Generated by Django 3.2.15 on 2022-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0034_kategori_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='foto',
            field=models.FileField(null=True, upload_to='images/kategoriler'),
        ),
    ]
