# Generated by Django 3.2.15 on 2022-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0036_auto_20221102_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='adet',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
