# Generated by Django 3.2.15 on 2022-11-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0037_alter_urun_adet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
