# Generated by Django 3.2.15 on 2022-11-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0041_auto_20221104_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparisler',
            name='adet',
        ),
        migrations.RemoveField(
            model_name='siparisler',
            name='fiyat',
        ),
    ]
