# Generated by Django 3.2.15 on 2022-11-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0042_auto_20221104_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Siparisler',
        ),
    ]
