# Generated by Django 3.2.15 on 2022-11-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0044_siparisler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisler',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.sepet'),
        ),
    ]
