# Generated by Django 3.2.15 on 2022-11-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0045_alter_siparisler_urun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siparisler',
            old_name='urun',
            new_name='sepettekiurun',
        ),
        migrations.AddField(
            model_name='siparisler',
            name='kullanicibilgileri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.order'),
        ),
    ]
