# Generated by Django 3.2.15 on 2022-11-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0046_auto_20221104_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='adi',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='adres',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='ilce',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='posta',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='sehir',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='soyadi',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='kartay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kartcvc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kartisim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kartno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kartyil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, default='x', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
