# Generated by Django 3.2.15 on 2022-11-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0048_auto_20221104_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adminnote',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
