# Generated by Django 3.2.15 on 2022-11-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0049_auto_20221104_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='{{user.email}} ', max_length=200),
        ),
    ]
