# Generated by Django 3.2.15 on 2022-11-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0052_auto_20221108_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='fiyat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
