# Generated by Django 3.2.15 on 2022-11-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0054_order_sepet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sepet',
        ),
    ]
