# Generated by Django 3.2.15 on 2022-11-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0055_remove_order_sepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sepets',
            field=models.ManyToManyField(to='urunler.Sepet'),
        ),
    ]
